INSERT INTO MANGER(EMAIL,PASSWORD) VALUES ('manger','123');
INSERT INTO DEPARTMENT(NAME) VALUES ('IT DEPT');
INSERT INTO STUDENT(EMAIL,NAME,PASSWORD ) VALUES ('Majd@Majd.com','Majd','123');
INSERT INTO ADMIN(EMAIL,NAME,PASSWORD,DEPARTMENT_ID) VALUES ('Admin@Admin.com','Admin','123',1);
INSERT INTO COURSE(CREDITS,NAME,DEPARTMENT_ID) VALUES (3,'IAP',1);